[WIP] Configurable cmd
jupyterhub/repo2docker pull request #957
Opened 2020-09-12 22:11 UTC by AliMirlou

A configurable CMD might not be something this project wants but there are many use-cases for this, like starting the notebook in a different way or even using Repo2Docker as a library to build non-jupyter Docker images. It would be nice to have this feature.

By the way, this change is completely **backward-compatible** and **does not affect** anyone who does not want to change the CMD.

2020-09-12 22:13 UTC, AliMirlou commented
I haven't reflected the changes in the documentations and changelog yet. Waiting for someone's approval first.

2020-09-13 11:15 UTC, AliMirlou commented
Also can anyone explain why the "lint" check is failing? Is it because of too many characters in one line?

2020-09-13 11:57 UTC, manics commented
We use pre-commit and the black autoformatter.

If you install pre-commit (e.g. with pip) and run

    pre-commit run --all-files

the code should pass the CI lint check.

2020-09-24 19:19 UTC, AliMirlou commented
@manics Can you review this PR yourself? It's not a major change.

2020-10-12 01:36 UTC, AliMirlou commented
@betatim I need some approval to continue this PR. Can you give a quick review?

2020-10-15 09:56 UTC, AliMirlou commented
Or @minrk perhaps?

2021-01-05 17:22 UTC, AliMirlou commented
@manics Can you review this PR now?

2022-10-30 19:36 UTC, consideRatio requested changes
I think it could be acceptable to provide this, but I'm not sure.

I made a few suggestions towards making me feel comfortable with the implementation. I think a very strong case needs to be made for a string replacement still though, and it probably needs to be documented if a strong case for it is presented.

2022-10-30 19:36 UTC, consideRatio commented on repo2docker/buildpacks/base.py
> +        This should return a list of strings to be used as Dockerfile `CMD`.
```suggestion
    def get_cmd(self):
        """
        A list of strings to be used for the Dockerfile's `CMD`.
```

2022-10-30 19:36 UTC, consideRatio commented on repo2docker/buildpacks/base.py
> +            )
- Removed validation as this isn't user facing, just for those making custom buildpacks. My goal is to minimize complexity and ease the long term maintenance and code comprehension by doing that.
- Removed tuples fixup for similar reasons.

```suggestion
        cmd = self.get_command()
        if isinstance(cmd, list):
            cmd = str(cmd).replace("'", '"')
```

I don't understand what is going on with regards to the replacement operation that remains, but I suspect its not reasonable to provide either.

2022-10-30 19:36 UTC, consideRatio commented on repo2docker/buildpacks/base.py
> +            command=cmd,
```suggestion
            cmd=cmd,
```

2022-10-30 19:36 UTC, consideRatio commented on repo2docker/buildpacks/base.py
> +CMD {{ command }}
```suggestion
CMD {{ cmd }}
```

2022-10-31 00:20 UTC, consideRatio commented
## Related
- https://github.com/jupyterhub/repo2docker/issues/1206

2024-09-15 18:28 UTC, closed without merging

2024-09-15 18:28 UTC, manics commented
Thanks for the PR. I'm closing since there's been no updates, and it's already possible to override `CMD` using appendix
https://repo2docker.readthedocs.io/en/latest/usage.html#cmdoption-jupyter-repo2docker-appendix